### ISSUE TITLE
Please drop authors file from your repo

### ISSUE THREAD

**Issue by cicku** [calfzhou/autoproxy-gfwlist#1]
Hi there,

I hope you are doing great. I and other people who have contributed to the gfwlist, don't want to see the email addresses being unveiled to the public. Incidentally, I've been struggling with spammers for years.

Please, eithor drop it completely or obfuscate the addresses.

**Comment by calfzhou** [comment]
@cicku I removed authors file, and will try to remove related commit history

**Comment by cicku** [comment]
Thank you.

**Comment by calfzhou** [comment]
history removed.
