### ISSUE TITLE
Close this repo

### ISSUE THREAD

**Issue by cicku** [calfzhou/autoproxy-gfwlist#7]
Hi,

In order to avoid potential collisions with [official gfwlist](https://github.com/gfwlist), I'm writing here to ask for the shutdown of this repo.

Thanks.

**Comment by calfzhou** [comment]
Your github repo have not updated for a long time, while the google code one is still activity updating. Are you going to give up the github repo?

**Comment by cicku** [comment]
No, the official place is not enabled yet.
